Dagger
KornilovMikhail/MVPAndroidProject pull request #4
Opened 2019-03-18 19:56 UTC by KornilovMikhail

2019-03-19 22:00 UTC, NailShaykhrazievItis requested changes

2019-03-19 22:00 UTC, NailShaykhrazievItis commented on app/build.gradle
> +    def dagger_version = "2.20"
2.21 последняя версия

2019-03-19 22:00 UTC, NailShaykhrazievItis commented on app/src/main/java/com/github/kornilovmikhail/mvpandroidproject/di/module/DBModule.kt
> +class DBModule {
если у тебя тут и репозиторий, то думаю будет уместнее DataModule в названии

2019-03-19 22:00 UTC, NailShaykhrazievItis commented on app/src/main/java/com/github/kornilovmikhail/mvpandroidproject/ui/main/adapter/EventAdapter.kt
> +    private val mainPresenter: MainPresenter
хммм странноватое решение, но видимо оно было принято из-за того, что я показывал, что можно инжектить и адаптеры через дагггер, но эт необязательно. Предыдущее решение было хорошим, тут не стоило рефакторить и не стоило инжектить адаптер через даггер. Прошу прощения, моя вина

2019-03-19 22:00 UTC, NailShaykhrazievItis commented on detekt/detekt-config.yml
> +    excludeAnnotatedProperties: "InjectPresenter, InjectExtra, Inject"
Тут лукас - умняга

2019-03-19 22:00 UTC, NailShaykhrazievItis commented on app/src/main/java/com/github/kornilovmikhail/mvpandroidproject/presenter/MainPresenter.kt
> +class MainPresenter (private val repo: EventsRepo, private val pagination: Pagination) :
А зачем инжектить сюда пагинейшен, если он есть уже в eventsRepo 🤔 
обращайтесь к пагинации через репу. И переименуйте класс - название не очевидное.  PaginationPreferences как пример ну или около того

2019-03-20 07:57 UTC, KornilovMikhail commented on app/src/main/java/com/github/kornilovmikhail/mvpandroidproject/ui/main/adapter/EventAdapter.kt
> +    private val mainPresenter: MainPresenter
Я подумал, что адаптер не должен хранить в себе данные

2019-03-25 19:35 UTC, NailShaykhrazievItis approved these changes

2019-03-25 19:40 UTC, merged